server:
  port: 8021

spring:
  application:
    name: service2 #스프링 컨피그의 디렉토리명 과 일치해야 함
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 # Eureka Server 에 heartbeat 를 보내는 빈도를 나타내며 기본값은 30초
    lease-expiration-duration-in-seconds: 2 # Server 레지스트리에서 설정된 시간동안 heartbeat를 받지 못하면 해당 Eureka Instance를 Registry에서 제거 (기본 90초)
  client:
    register-with-eureka: true # 유레카 서비스에 등록 여부
    fetch-registry: true
    registryFetchIntervalSeconds: 5 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"